version: '3.8'

services:
  restack:
    image: ghcr.io/restackio/engine:main
    container_name: restack-studio
    ports:
      - "5233:5233"
      - "6233:6233"
      - "7233:7233"
    networks:
      - compllama-network

  chromadb:
    image: chromadb/chroma:latest  # Uses the chromadb/chroma image from Docker Hub
    container_name: chromadb
    ports:
      - "8001:8000"  # Expose the port ChromaDB runs on, adjust if needed
    environment:
      - CHROMA_DB_PATH=/data  # Specify data path within the container
      - CHROMA_LOG_LEVEL=INFO # Set log level, can be adjusted as needed
    volumes:
      - chromadb_data:/data   # Mount a volume for persistent data storage
    networks:
      - compllama-network

  chroma-ui:
    image: ghcr.io/chroma-core/chroma-ui:main
    environment:
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "3000:3000"
    depends_on:
      - chromadb
    networks:
      - compllama-network

networks:
  compllama-network:
    driver: bridge

volumes:
  chromadb_data: