version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest  # Uses the chromadb/chroma image from Docker Hub
    container_name: chromadb
    ports:
      - "8001:8000"  # Expose the port ChromaDB runs on, adjust if needed
    environment:
      - CHROMA_DB_PATH=/data  # Specify data path within the container
      - CHROMA_LOG_LEVEL=INFO # Set log level, can be adjusted as needed
    volumes:
      - chromadb_data:/data   # Mount a volume for persistent data storage

volumes:
  chromadb_data: